services:
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/simplechat
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Br!ggs1882
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: simplechat
      MYSQL_ROOT_PASSWORD: Br!ggs1882
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 10s
        timeout: 5s
        retries: 5