app = "chat-service"
primary_region = "yyz"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443
