name: Deploy Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Database
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy -c ./simple-chat-db/fly.toml

      - name: Deploy Backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DB_URL: jdbc:mysql://simple-chat-db.internal:3306/simplechat
          DB_USERNAME: chatservice-user
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: flyctl deploy -c ./chat-service/fly.toml
