name: Deploy Chat Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      run: |
        docker build -t mustafaashfaq/chat-service:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push mustafaashfaq/chat-service:latest

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        DB_URL: jdbc:mysql://simple-chat-db.internal:3306/simplechat
        DB_USERNAME: chatservice-user
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        flyctl deploy
