name: Deploy Chat Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "$HOME/.fly/bin" >> $GITHUB_PATH  # Add Flyctl to the system-wide path

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        
    - name: Build and Push Docker Image
      env:
        PATH: $HOME/.fly/bin:$PATH  # Ensure Flyctl is in the path
      run: |
        docker build -t your-dockerhub-username/chat-service:latest ./chat-service
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push your-dockerhub-username/chat-service:latest

    - name: Deploy to Fly.io
      env:
        PATH: $HOME/.fly/bin:$PATH  # Ensure Flyctl is in the path
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        DB_URL: jdbc:mysql://simple-chat-db.internal:3306/simplechat
        DB_USERNAME: chatservice-user
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        flyctl deploy